---
title: "Benchmark overview"
author: "Colin Gillespie"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Benchmark overview}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---


# Overview

There are two main benchmarks in this package:

  * `benchmark_std()`
    - This consists of three sub benchmarks: `benchmark_prog`, 
    `benchmark_matrix_cal`, and `benchmark_matrix_fun`
  * `benchmark_io()`
    - This consists of two sub benchmarks: `read` and `write`.

# Programming benchmarks (`prog`)

The `benchmark_prog` benchmark consists of timing five matrix programming operations: 

  * $3,500,000$ Fibonacci numbers calculation (vector calc) - `bm_prog_fib`.
  * Creation of a $3500 \times 3500$ Hilbert matrix (matrix calc) - `bm_prog_hilbert`.
  * Grand common divisors of $1,000,000$ pairs (recursion) - `bm_prog_gcd`.
  * Creation of a $1600\times 1600$ Toeplitz matrix (loops) - `bm_prog_toeplitz`.
  * Escoufier's method on a $60\times 60$ matrix (mixed) - `bm_prog_escoufier`.

# Matrix calulations (`matrix_cal`)

A collection of matrix benchmark functions aimed at assessing the calculation speed.

  * Creation, transp., deformation of a $2500\times 2500$ matrix - `bm_matrix_cal_manip`.
  * $2500\times2500$ normal distributed random matrix ^1000 - `bm_matrix_cal_power`.
  * Sorting of $7,000,000$ random values - `bm_matrix_cal_sort`.
  * $2500\times 2500$ cross-product matrix ($b = a' \times a$) - `bm_matrix_cal_cross_product`
  * Linear regression over a $3000 \times 3000$ matrix - `bm_matrix_cal`.

# Matrix fun (`matrix_fun`)

A collection of matrix benchmark functions

  * FFT over $2,500,000$ random values - `bm_matrix_fun_fft`.
  * Eigenvalues of a $640\times 640$ random matrix - `bm_matrix_fun_eigen`.
  * Determinant of a $2500 \times 2500$ random matrix - `bm_matrix_fun_determinant`.
  * Cholesky decomposition of a $3000 \times 3000$ matrix - `bm_matrix_fun_cholesky`.
  * Inverse of a $1600 \times 1600$ random matrix - `bm_matrix_fun_inverse`.

# Input/Output (`io`)

  * Reading a $5$, $50$ and $200$MB csv file
  * Writing a $5$, $50$ and $200$MB csv file
  
The purpose of this benchmark isn't to compare `write.csv` to another package. Instead, 
we went to assess your machine.


--- 

These benchmarks have been developed by many [authors](http://r.research.att.com/benchmarks/R-benchmark-25.R). 
